#!/bin/sh

echo 'root:orangepi' | chpasswd
mkdir /home/orangepi
chown orangepi.orangepi /home/orangepi
useradd orangepi
usermod -a -G sudo orangepi
echo 'orangepi:orangepi' | chpasswd
deluser --remove-home pi

