#!/bin/sh

echo "Update the system software"
apt update
apt -y full-upgrade

echo "Install Python Pip"
apt install -y python3-pip
echo "Install bottle and requests"
runuser -l orangepi -c "pip3 install bottle requests pytz PyP100"

echo "Get the resource pack"
runuser -l orangepi -c "wget https://rbrheating.com/resources/rbr.tgz"
echo "Unpack resources"
runuser -l orangepi -c "tar zxf rbr.tgz"
echo "Remove the resource pack"
runuser -l orangepi -c "rm rbr.tgz"
echo "Set up cron"
runuser -l orangepi -c "crontab crondata.txt"

runuser -l orangepi -c "echo orangepi >mypass"
runuser -l orangepi -c "echo wlan0 >network"
runuser -l orangepi -c "hostname -I >ip"

reboot
