#!/bin/sh

wget https://rbrheating.com/resources/rbr.tgz
tar zxf rbr.tgz
rm -f rbr.tgz
sudo apt update
sudo apt -y full-upgrade
echo "Get required Python modules"
sudo apt install -y python3-pip
pip3 install pytz bottle requests
rm setup
