#!/bin/sh

# Setup for Raspberry Pi - Raspbian headless

wget https://rbrheating.com/resources/rbr.tgz
tar zxf rbr.tgz
rm -f rbr.tgz
sudo apt update
sudo apt -y upgrade
echo "Get required Python modules"
sudo apt install -y python3-pip
pip3 install pytz bottle requests pytz PyP100
rm setup
