#!/bin/sh

# Setup for Orange Pi Zero 2 - Debian Desktop OS

echo "Update the system software"
apt update
apt -y upgrade

echo "Install Python Pip"
apt install -y python3-pip
echo "Install bottle and requests"
runuser -l orangepi -c "pip3 install bottle requests pytz PyP100"

echo "Get the resource pack"
runuser -l orangepi -c "wget https://rbrheating.com/resources/rbr.tgz"
echo "Unpack resources"
runuser -l orangepi -c "tar zxf rbr.tgz"
echo "Remove the resource pack"
runuser -l orangepi -c "rm rbr.tgz"
echo "Set up cron"
runuser -l orangepi -c "crontab crondata.txt"
crontab cronroot.txt

runuser -l orangepi -c "echo orangepi >mypass"
runuser -l orangepi -c "echo wlxe84e0626cdcb >network"
runuser -l orangepi -c "hostname -I >ip"

reboot
