#!/bin/sh

# Setup for Orange Pi Zero 2 - Debian Desktop OS

echo "Update the system"
sudo apt update
sudo apt -y upgrade

echo "Install Python Pip"
sudo apt install -y python3-pip
echo "Install python libraries"
pip3 install bottle requests pytz PyP100
sudo apt install -y python-tk
sudo rm -rf /usr/lib/python3/dist-packages/PIL
sudo rm -rf /usr/lib/python3/dist-packages/Pillow*
pip install pillow

wget https://rbrheating.com/resources/guidist.tgz
tar zxf guidist.tgz
crontab crondata.txt
sudo crontab crondata-root.txt

echo "Rebooting now..."
sudo reboot
