#!/bin/sh
pip install -U easycoder
cd ~/bin
mkdir -p rbrdev
cd rbrdev
rm -rf rbrdev rbr.tgz rbr
wget https://raw.githubusercontent.com/easycoder/rbr/refs/heads/main/dev/rbrdev
wget https://raw.githubusercontent.com/easycoder/rbr/refs/heads/main/dev/rbr.tgz
chmod a+x rbrdev
tar zxf rbr.tgz
cd rbr
easycoder main.ecs
