#!/bin/sh
pip install -U easycoder
cd ~/bin
rm -rf rbr
mkdir -p rbr
cd rbr
wget https://raw.githubusercontent.com/easycoder/rbr/refs/heads/main/dev/rbr.ecs
wget https://raw.githubusercontent.com/easycoder/rbr/refs/heads/main/dev/devices.ecs
easycoder rbr.ecs
