#!/bin/sh
pip install -U easycoder
rm rbrsim ~/bin/rbrsim
wget https://raw.githubusercontent.com/easycoder/rbr/refs/heads/main/dev/rbrsim
chmod a+x rbrsim
mv rbrsim ~/bin/rbrsim
wget https://raw.githubusercontent.com/easycoder/rbr/refs/heads/main/dev/environment.csv
rm -rf rbr
mkdir -p rbr
cd rbr
wget https://raw.githubusercontent.com/easycoder/rbr/refs/heads/main/dev/rbr/rbr.ecs
wget https://raw.githubusercontent.com/easycoder/rbr/refs/heads/main/dev/rbr/devices.ecs
easycoder rbr.ecs
