#!/bin/sh
pip install -U easycoder
https://raw.githubusercontent.com/easycoder/rbr/refs/heads/main/dev/setup.ecs
easycoder setup.ecs
cd ~/bin
https://raw.githubusercontent.com/easycoder/rbr/refs/heads/main/dev/rbrsim
chmod a+x rbrsim
