#!/bin/sh

# Setup for Orange Pi Zero 2 - Debian Server OS

echo "Update the system"
apt update
apt -y upgrade

echo "Install Python Pip"
apt install -y python3-dev
apt install -y python3-pip
echo "Install python libraries"
pip3 install bottle requests pytz PyP100 psutils

wget https://rbrheating.com/resources/dist.tgz
tar zxf dist.tgz
cp system/hosts /etc/hosts
crontab crondata.txt

echo
echo "Set the user password"
passwd
echo "Rebooting now..."
reboot
