#!/bin/sh

# Setup for Orange Pi Zero 2 - Debian Server OS

echo
echo "Set the user password"
passwd

echo "Update the system"
sudo apt update
sudo apt -y upgrade

sudo apt install -y apache2 ufw php libapache2-mod-php python3-dev python3-pip libglib2.0-dev

echo "Install python libraries"
sudo pip3 install requests pytz PyP100 psutil bluepy

sudo mkdir /mnt/data
sudo chmod a+w /mnt/data

sudo rm -r /var/www/html
sudo chmod a+w /var/www
ln -s /home/orangepi /var/www/html

wget https://rbrheating.com/home/dist.tgz
tar zxf dist.tgz
rm backup mac map dist.tgz
sudo crontab cronroot.txt
crontab crondata.txt

sudo cp system/hosts /etc/hosts
sudo cp system/dnsmasq.conf /etc/dnsmasq.conf
sudo cp system/hostapd.conf /etc/hostapd.conf

ip -o link | awk '$2 != "lo:" {print $2, $(NF-2)}'>interfaces
python3 getmac.py >mac
echo
echo "After the reboot, type 'cat mac' to get the MAC address of the interface connecting to the Internet."
echo "Use this to construct a unique SSID for your local access point (hotspot)."
echo "Run 'sudo nano /etc/hostapd.conf', edit the fields containing 'XXXXXXXXXX' then type 'reboot'"

echo
echo "Rebooting now"

sudo reboot
