#!/bin/sh
pip install -U easycoder
cd ~/bin
mkdir -p rbr_dev
cd rbr_dev
rm -rf rbr.tgz rbr
wget https://raw.githubusercontent.com/easycoder/rbr/refs/heads/main/dev/rbrdev
wget https://raw.githubusercontent.com/easycoder/rbr/refs/heads/main/dev/rbr.tgz
chmod a+x rbrdev
rm ../rbrdev
mv rbrdev ..
tar zxf rbr.tgz
cd rbr
easycoder main.ecs
